import { titleFont } from "@/config/fonts";

import type { Metadata } from "next";
import type { ILayoutProps } from "@/interfaces/components.interfaces";

import "./globals.css";

export const metadata: Metadata = {
    title: "Task Manager",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: ILayoutProps) {
    return (
        <html lang="en">
            <body className={`${titleFont.className} antialiased`}>
                {children}
            </body>
        </html>
    );
}
